default_config:

homeassistant:
  debug: true

logger:
  default: info
  logs:
    custom_components.template_climate: debug

climate:
  - platform: template_climate
    name: Test Thermostat
    modes:
      - "auto"
      - "heat"
      - "off"
    min_temp: 5
    max_temp: 30
